export const ApiErrorKeys = {
  notAuthenticated: "apiErrors.notAuthenticated",
  databaseNotConfigured: "apiErrors.databaseNotConfigured",
  general: {
    forbidden: "apiErrors.general.forbidden",
    notFound: "apiErrors.general.notFound",
    failed: "apiErrors.general.failed",
    invalid: "apiErrors.general.invalid",
  },
  auth: {
    oauth: {
      disabled: "apiErrors.auth.oauth.disabled",
      failedToGenerateUrl: "apiErrors.auth.oauth.failedToGenerateUrl",
      githubNotConfigured: "apiErrors.auth.oauth.githubNotConfigured",
      googleNotConfigured: "apiErrors.auth.oauth.googleNotConfigured",
      linuxdoNotConfigured: "apiErrors.auth.oauth.linuxdoNotConfigured",
    },
    logout: {
      failed: "apiErrors.auth.logout.failed",
    },
    verificationCode: {
      emailServiceNotConfigured: "apiErrors.auth.verificationCode.emailServiceNotConfigured",
      sendFailed: "apiErrors.auth.verificationCode.sendFailed",
    },
    register: {
      qqEmailOnly: "apiErrors.auth.register.qqEmailOnly",
    },
    me: {
      failedToGetUser: "apiErrors.auth.me.failedToGetUser",
    },
    passkey: {
      notConfigured: "apiErrors.auth.passkey.notConfigured",
      challengeExpired: "apiErrors.auth.passkey.challengeExpired",
      verificationFailed: "apiErrors.auth.passkey.verificationFailed",
      alreadyExists: "apiErrors.auth.passkey.alreadyExists",
      registrationFailed: "apiErrors.auth.passkey.registrationFailed",
      authenticationFailed: "apiErrors.auth.passkey.authenticationFailed",
    },
  },
  admin: {
    users: {
      failedToFetch: "apiErrors.admin.users.failedToFetch",
      userNotFound: "apiErrors.admin.users.userNotFound",
      noFieldsToUpdate: "apiErrors.admin.users.noFieldsToUpdate",
      onlySuperAdminCanModifyRoles: "apiErrors.admin.users.onlySuperAdminCanModifyRoles",
      adminCannotModifyOtherAdmins: "apiErrors.admin.users.adminCannotModifyOtherAdmins",
      failedToUpdate: "apiErrors.admin.users.failedToUpdate",
      reapplyNotAvailable: "apiErrors.admin.users.reapplyNotAvailable",
      reapplyAlreadyUnlocked: "apiErrors.admin.users.reapplyAlreadyUnlocked",
      failedToResetReapply: "apiErrors.admin.users.failedToResetReapply",
      cannotDeleteSelf: "apiErrors.admin.users.cannotDeleteSelf",
      failedToDelete: "apiErrors.admin.users.failedToDelete",
    },
    messages: {
      messageNotFound: "apiErrors.admin.messages.messageNotFound",
      alreadyRevoked: "apiErrors.admin.messages.alreadyRevoked",
      failedToFetch: "apiErrors.admin.messages.failedToFetch",
      failedToFetchSingle: "apiErrors.admin.messages.failedToFetchSingle",
      roleRequired: "apiErrors.admin.messages.roleRequired",
      statusRequired: "apiErrors.admin.messages.statusRequired",
      recipientsRequired: "apiErrors.admin.messages.recipientsRequired",
      noRecipientsFound: "apiErrors.admin.messages.noRecipientsFound",
      failedToCreate: "apiErrors.admin.messages.failedToCreate",
      failedToUpdate: "apiErrors.admin.messages.failedToUpdate",
      failedToRevoke: "apiErrors.admin.messages.failedToRevoke",
    },
    inviteCodes: {
      failedToFetch: "apiErrors.admin.inviteCodes.failedToFetch",
      invalidExpiry: "apiErrors.admin.inviteCodes.invalidExpiry",
      expiryMustBeInFuture: "apiErrors.admin.inviteCodes.expiryMustBeInFuture",
      noValid: "apiErrors.admin.inviteCodes.noValid",
      failedToImport: "apiErrors.admin.inviteCodes.failedToImport",
      failedToCreate: "apiErrors.admin.inviteCodes.failedToCreate",
      storageDisabled: "apiErrors.admin.inviteCodes.storageDisabled",
      queryTokenFailed: "apiErrors.admin.inviteCodes.queryTokenFailed",
      noValidFound: "apiErrors.admin.inviteCodes.noValidFound",
      notFound: "apiErrors.admin.inviteCodes.notFound",
      alreadyUsed: "apiErrors.admin.inviteCodes.alreadyUsed",
      alreadyExpired: "apiErrors.admin.inviteCodes.alreadyExpired",
      alreadyAssigned: "apiErrors.admin.inviteCodes.alreadyAssigned",
      alreadyIssued: "apiErrors.admin.inviteCodes.alreadyIssued",
      failedToInvalidate: "apiErrors.admin.inviteCodes.failedToInvalidate",
      failedToUpdateUsage: "apiErrors.admin.inviteCodes.failedToUpdateUsage",
      failedToIssue: "apiErrors.admin.inviteCodes.failedToIssue",
      userIdRequired: "apiErrors.admin.inviteCodes.userIdRequired",
      emailRequired: "apiErrors.admin.inviteCodes.emailRequired",
      emailNotificationsDisabled: "apiErrors.admin.inviteCodes.emailNotificationsDisabled",
      alreadyDeleted: "apiErrors.admin.inviteCodes.alreadyDeleted",
      failedToDelete: "apiErrors.admin.inviteCodes.failedToDelete",
      assign: {
        notFound: "apiErrors.admin.inviteCodes.assign.notFound",
        alreadyUsed: "apiErrors.admin.inviteCodes.assign.alreadyUsed",
        expired: "apiErrors.admin.inviteCodes.assign.expired",
        alreadyAssigned: "apiErrors.admin.inviteCodes.assign.alreadyAssigned",
        alreadyIssued: "apiErrors.admin.inviteCodes.assign.alreadyIssued",
        userIdRequired: "apiErrors.admin.inviteCodes.assign.userIdRequired",
        emailRequired: "apiErrors.admin.inviteCodes.assign.emailRequired",
        userNotFound: "apiErrors.admin.inviteCodes.assign.userNotFound",
        notificationsDisabled: "apiErrors.admin.inviteCodes.assign.notificationsDisabled",
      },
    },
    preApplications: {
      failedToFetch: "apiErrors.admin.preApplications.failedToFetch",
      historyFetchFailed: "apiErrors.admin.preApplications.historyFetchFailed",
      failedToReview: "apiErrors.admin.preApplications.failedToReview",
      approvalRevokeFailed: "apiErrors.admin.preApplications.approvalRevokeFailed",
      approvalNotRevocable: "apiErrors.admin.preApplications.approvalNotRevocable",
      approvalRevokeInviteAlreadyUsed:
        "apiErrors.admin.preApplications.approvalRevokeInviteAlreadyUsed",
      approvalRevokeFormalFeedbackExists:
        "apiErrors.admin.preApplications.approvalRevokeFormalFeedbackExists",
      inviteCodeRequired: "apiErrors.admin.preApplications.inviteCodeRequired",
      invalidInviteExpiry: "apiErrors.admin.preApplications.invalidInviteExpiry",
      expiryMustBeInFuture: "apiErrors.admin.preApplications.expiryMustBeInFuture",
      alreadyReviewed: "apiErrors.admin.preApplications.alreadyReviewed",
      pendingAppealExists: "apiErrors.admin.preApplications.pendingAppealExists",
      shadowbanLocked: "apiErrors.admin.preApplications.shadowbanLocked",
      aiNotConfigured: "apiErrors.admin.preApplications.aiNotConfigured",
      aiReviewFailed: "apiErrors.admin.preApplications.aiReviewFailed",
      duplicateCheckFailed: "apiErrors.admin.preApplications.duplicateCheckFailed",
      notes: {
        failedToFetch: "apiErrors.admin.preApplications.notes.failedToFetch",
        failedToCreate: "apiErrors.admin.preApplications.notes.failedToCreate",
        failedToUpdate: "apiErrors.admin.preApplications.notes.failedToUpdate",
        failedToDelete: "apiErrors.admin.preApplications.notes.failedToDelete",
        notFound: "apiErrors.admin.preApplications.notes.notFound",
        permissionDenied: "apiErrors.admin.preApplications.notes.permissionDenied",
        alreadyDeleted: "apiErrors.admin.preApplications.notes.alreadyDeleted",
      },
    },
    preApplicationAppeals: {
      failedToFetch: "apiErrors.admin.preApplicationAppeals.failedToFetch",
      failedToReview: "apiErrors.admin.preApplicationAppeals.failedToReview",
      notFound: "apiErrors.admin.preApplicationAppeals.notFound",
      alreadyReviewed: "apiErrors.admin.preApplicationAppeals.alreadyReviewed",
      invalidAction: "apiErrors.admin.preApplicationAppeals.invalidAction",
      targetChanged: "apiErrors.admin.preApplicationAppeals.targetChanged",
      archivedPreApplication: "apiErrors.admin.preApplicationAppeals.archivedPreApplication",
      originalReviewer: "apiErrors.admin.preApplicationAppeals.originalReviewer",
      reviewRequestInitiator: "apiErrors.admin.preApplicationAppeals.reviewRequestInitiator",
    },
    posts: {
      failedToFetch: "apiErrors.admin.posts.failedToFetch",
      postNotFound: "apiErrors.admin.posts.postNotFound",
      failedToFetchSingle: "apiErrors.admin.posts.failedToFetchSingle",
      failedToUpdate: "apiErrors.admin.posts.failedToUpdate",
      failedToDelete: "apiErrors.admin.posts.failedToDelete",
      failedToCreate: "apiErrors.admin.posts.failedToCreate",
    },
    settings: {
      failedToLoad: "apiErrors.admin.settings.failedToLoad",
      failedToUpdate: "apiErrors.admin.settings.failedToUpdate",
    },
    systemConfig: {
      failedToFetch: "apiErrors.admin.systemConfig.failedToFetch",
      failedToUpdate: "apiErrors.admin.systemConfig.failedToUpdate",
    },
    shadowBan: {
      failedToFetch: "apiErrors.admin.shadowBan.failedToFetch",
      failedToSave: "apiErrors.admin.shadowBan.failedToSave",
      failedToDelete: "apiErrors.admin.shadowBan.failedToDelete",
      userNotFound: "apiErrors.admin.shadowBan.userNotFound",
      notFound: "apiErrors.admin.shadowBan.notFound",
    },
    resetDatabase: {
      failed: "apiErrors.admin.resetDatabase.failed",
    },
    clearUserSessions: {
      failed: "apiErrors.admin.clearUserSessions.failed",
    },
    stats: {
      failedToFetch: "apiErrors.admin.stats.failedToFetch",
    },
    emailLogs: {
      failed: "apiErrors.admin.emailLogs.failed",
    },
    manualOutbound: {
      failed: "apiErrors.admin.manualOutbound.failed",
      userNotFound: "apiErrors.admin.manualOutbound.userNotFound",
      recipientEmailRequired: "apiErrors.admin.manualOutbound.recipientEmailRequired",
    },
    apiTokens: {
      failedToFetch: "apiErrors.admin.apiTokens.failedToFetch",
      failedToCreate: "apiErrors.admin.apiTokens.failedToCreate",
      failedToRevoke: "apiErrors.admin.apiTokens.failedToRevoke",
      maxTokensReached: "apiErrors.admin.apiTokens.maxTokensReached",
      tokenNotFound: "apiErrors.admin.apiTokens.tokenNotFound",
      notOwner: "apiErrors.admin.apiTokens.notOwner",
    },
  },
  dashboard: {
    password: {
      passwordsDoNotMatch: "apiErrors.dashboard.password.passwordsDoNotMatch",
      currentPasswordRequired: "apiErrors.dashboard.password.currentPasswordRequired",
      invalidCurrentPassword: "apiErrors.dashboard.password.invalidCurrentPassword",
      failedToUpdate: "apiErrors.dashboard.password.failedToUpdate",
    },
    messages: {
      failedToFetch: "apiErrors.dashboard.messages.failedToFetch",
      failedToFetchSingle: "apiErrors.dashboard.messages.failedToFetchSingle",
      failedToMarkAsRead: "apiErrors.dashboard.messages.failedToMarkAsRead",
      failedToDelete: "apiErrors.dashboard.messages.failedToDelete",
      summary: {
        failedToFetch: "apiErrors.dashboard.messages.summary.failedToFetch",
      },
    },
    posts: {
      failedToFetch: "apiErrors.dashboard.posts.failedToFetch",
      failedToFetchSingle: "apiErrors.dashboard.posts.failedToFetchSingle",
      postNotFound: "apiErrors.dashboard.posts.postNotFound",
      failedToCreate: "apiErrors.dashboard.posts.failedToCreate",
      failedToUpdate: "apiErrors.dashboard.posts.failedToUpdate",
      failedToDelete: "apiErrors.dashboard.posts.failedToDelete",
    },
    profile: {
      failedToUpdate: "apiErrors.dashboard.profile.failedToUpdate",
    },
    account: {
      failedToDelete: "apiErrors.dashboard.account.failedToDelete",
    },
    inviteCodes: {
      failedToFetch: "apiErrors.dashboard.inviteCodes.failedToFetch",
      failedToContribute: "apiErrors.dashboard.inviteCodes.failedToContribute",
      failedToDelete: "apiErrors.dashboard.inviteCodes.failedToDelete",
      failedToSend: "apiErrors.dashboard.inviteCodes.failedToSend",
      noValid: "apiErrors.dashboard.inviteCodes.noValid",
      notFound: "apiErrors.dashboard.inviteCodes.notFound",
      notOwner: "apiErrors.dashboard.inviteCodes.notOwner",
      cannotDeleteUsed: "apiErrors.dashboard.inviteCodes.cannotDeleteUsed",
      cannotDeleteAssigned: "apiErrors.dashboard.inviteCodes.cannotDeleteAssigned",
      cannotDeleteClaimed: "apiErrors.dashboard.inviteCodes.cannotDeleteClaimed",
      alreadyExists: "apiErrors.dashboard.inviteCodes.alreadyExists",
      alreadyUsed: "apiErrors.dashboard.inviteCodes.alreadyUsed",
      alreadyClaimed: "apiErrors.dashboard.inviteCodes.alreadyClaimed",
      alreadySent: "apiErrors.dashboard.inviteCodes.alreadySent",
      expired: "apiErrors.dashboard.inviteCodes.expired",
      userNotFound: "apiErrors.dashboard.inviteCodes.userNotFound",
      cannotSendToSelf: "apiErrors.dashboard.inviteCodes.cannotSendToSelf",
      linuxdoRequired: "apiErrors.dashboard.inviteCodes.linuxdoRequired",
    },
    applyAdmin: {
      failed: "apiErrors.dashboard.applyAdmin.failed",
      alreadyAdmin: "apiErrors.dashboard.applyAdmin.alreadyAdmin",
      alreadyApplied: "apiErrors.dashboard.applyAdmin.alreadyApplied",
      noSuperAdmin: "apiErrors.dashboard.applyAdmin.noSuperAdmin",
      disabled: "apiErrors.dashboard.applyAdmin.disabled",
    },
    passkeys: {
      failedToFetch: "apiErrors.dashboard.passkeys.failedToFetch",
      notFound: "apiErrors.dashboard.passkeys.notFound",
      failedToDelete: "apiErrors.dashboard.passkeys.failedToDelete",
    },
  },
  preApplication: {
    failedToFetch: "apiErrors.preApplication.failedToFetch",
    failedToLoadDraft: "apiErrors.preApplication.failedToLoadDraft",
    failedToSaveDraft: "apiErrors.preApplication.failedToSaveDraft",
    failedToDeleteDraft: "apiErrors.preApplication.failedToDeleteDraft",
    failedToSubmit: "apiErrors.preApplication.failedToSubmit",
    failedToDelete: "apiErrors.preApplication.failedToDelete",
    alreadySubmitted: "apiErrors.preApplication.alreadySubmitted",
    alreadyApproved: "apiErrors.preApplication.alreadyApproved",
    inviteCodeReceived: "apiErrors.preApplication.inviteCodeReceived",
    essayTooShort: "apiErrors.preApplication.essayTooShort",
    essayTooLong: "apiErrors.preApplication.essayTooLong",
    draftTooLong: "apiErrors.preApplication.draftTooLong",
    invalidEmailDomain: "apiErrors.preApplication.invalidEmailDomain",
    invalidGroup: "apiErrors.preApplication.invalidGroup",
    sourceDetailRequired: "apiErrors.preApplication.sourceDetailRequired",
    noPreApplicationFound: "apiErrors.preApplication.noPreApplicationFound",
    versionConflict: "apiErrors.preApplication.versionConflict",
    resubmitLimitExceeded: "apiErrors.preApplication.resubmitLimitExceeded",
    failedToUpdate: "apiErrors.preApplication.failedToUpdate",
    aiPreviewNotConfigured: "apiErrors.preApplication.aiPreviewNotConfigured",
    aiPreviewFailed: "apiErrors.preApplication.aiPreviewFailed",
    editTooFrequent: "apiErrors.preApplication.editTooFrequent",
    submitBanned: "apiErrors.preApplication.submitBanned",
    submitWindowClosed: "apiErrors.preApplication.submitWindowClosed",
    dailyUserLimitExceeded: "apiErrors.preApplication.dailyUserLimitExceeded",
    dailyGlobalLimitExceeded: "apiErrors.preApplication.dailyGlobalLimitExceeded",
    submitRateServiceUnavailable: "apiErrors.preApplication.submitRateServiceUnavailable",
    reapplyNotAvailable: "apiErrors.preApplication.reapplyNotAvailable",
    reapplyStartRequired: "apiErrors.preApplication.reapplyStartRequired",
    reapplyAlreadyStarted: "apiErrors.preApplication.reapplyAlreadyStarted",
    failedToStartReapply: "apiErrors.preApplication.failedToStartReapply",
    formalApprovalFeedback: {
      failedToSubmit: "apiErrors.preApplication.formalApprovalFeedback.failedToSubmit",
      notAllowed: "apiErrors.preApplication.formalApprovalFeedback.notAllowed",
    },
    appeal: {
      failedToFetch: "apiErrors.preApplication.appeal.failedToFetch",
      failedToCreate: "apiErrors.preApplication.appeal.failedToCreate",
      disabled: "apiErrors.preApplication.appeal.disabled",
      preApplicationNotRejected: "apiErrors.preApplication.appeal.preApplicationNotRejected",
      pendingAppealExists: "apiErrors.preApplication.appeal.pendingAppealExists",
      cooldownActive: "apiErrors.preApplication.appeal.cooldownActive",
    },
  },
} as const
